services:
  frontend:
    build:
      context: frontend
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          initial_sync: true
        - action: rebuild
          path: ./frontend/package.json
    # volumes:
    #   - ./frontend:/app
    command: >
      sh -c "npm run dev"